networks:
  walnut-dev:

services:
  walnut_postgres:
    restart: always
    container_name: walnut_postgres
    image: postgres:17.0-alpine
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=walnutdev
    networks:
      - walnut-dev
    ports:
      - 1234:5432

  walnut-server:
    restart: always
    container_name: walnut-server-dev
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@walnut_postgres:5432/walnutdev
      - TELEGRAM_BOT_API_KEY=
      - TELEGRAM_WALNUT_NOTIFICATIONS_CHAT_ID=
      - UNIVERSAL_SIERRA_COMPILER=./universal-sierra-compiler
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - S3_ENDPOINT=
      - S3_REGION=
      - CLASSES_S3_BUCKET_NAME=walnutserver-east-1-classes-verification
      - BINARIES_S3_BUCKET_NAME=
      - BINARIES_SAVE_DIRECTORY_PATH=/opt/app/binaries
      - SCARB_GITHUB_REPO_NAME=software-mansion/scarb
      - SCARB_LATEST_VERSION_FILE_NAME=/opt/app/binaries/scarb_latest_version.txt
      - SCARB_RUN_SCHEDULER_INTERVAL_MINUTES=60
      - DOJO_GITHUB_REPO_NAME=dojoengine/dojo
      - DOJO_LATEST_VERSION_FILE_NAME=/opt/app/binaries/sozo_latest_version.txt
      - DOJO_RUN_SCHEDULER_INTERVAL_MINUTES=60
      - LOG_LEVEL=INFO
      - BUILD_CPU_LIMIT=300
    volumes:
      - ./docker-volumes/walnut-server/binaries:/opt/app/binaries:rw
      - ./docker-volumes/walnut-server/verifications:/opt/app/tmp:rw
    depends_on:
      - walnut_postgres
    networks:
      - walnut-dev
    ports:
      - 3000:3000
